[package]
name = "vga_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
x86_64 = "*"

[build-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

